POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Inl1eW8iLCJpZCI6IjYxMjhmM2I3Njk4NmJlMjNhODhiZTM5NiIsImlhdCI6MTYzMDM0NTQ5OCwiZXhwIjoxNjMwMzQ5MDk4fQ.1AUqoa4iqm8Wqxr2mqHS0HPAvRvZlQ7Q6iRH3SWiuew

{
    "content": "Nota para editar",
    "important": true
}
